<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

    <div class="jumbotron">
        <h1>Bem Vindo</h1>
        <p>
            produtos Alimentos :
        </p>
    </div>

    <div class="col-md-12">
        <?php foreach($this->products as $product):?>
        <div class="col-md-4">
            <img src="<?=$product['image'];?>" 
                 alt="" class="img-responsive">
            <h2>
                <a href="<?=HOME;?>/product/<?=$product['id'];?>">
                    <?=$product['name'];?>
                </a>
            </h2>
            <p>
                <?=$product['description'];?>
            </p>
            <p>
                R$ <?=number_format($product['price'], 2, ',', '.');?>
            </p>
        </div>
        <?php endforeach;?>
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
