
version: '3.3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://pguser:postgres@postgres
      TIME_ZONE: 'Brasilia'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    ports:
      - 8080:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres